### ISSUE TITLE
Add timer functionality

### ISSUE THREAD

**Issue by meck** [DWilliames/idasen-controller-mac#1]
Thanks for a great app! I previously forked another swift app with the same purpose and hacked in some basic support for a standing timer [here](https://github.com/meck/LinakDeskControl) However your implementation seems to work better when moving, and is very nicely polished.

But some optional timer functionality would be nice. No matter how accessible it is i still seem to forget to stand... :facepalm:

**Comment by ohkimur** [comment]
@DWilliames As I said in the PR, I would love to see this functionality implemented.

**Comment by DWilliames** [comment]
Finally got around to merging this in!! Thanks for your work on it @meck
