### ISSUE TITLE
Script Command move to height

### ISSUE THREAD

**Issue by davidmondok** [DWilliames/idasen-controller-mac#14]
First, thanks for this app. I love it. I control it via Raycast and it works perfectly.

Were it possible to add another command `to-position` that accepts a height number? That would allow one to create custom Alfred/Raycast commands like "Move to presentation height".

cheers

**Comment by DWilliames** [comment]
Just released an update to support this.

Use it like this:
```
tell application "Desk Controller"
	move to "120cm"
end tell
```

`move to "120cm"`: Will move the desk to a height of 120cm

`move to "55in"`: Will move the desk to a height of 55 inches

`move to "80"`: Will move the desk to a height of either 80cm or 80in depending on your preferences

[Download it here](https://github.com/DWilliames/idasen-controller/releases/latest/download/Desk.Controller.app.zip)
