### ISSUE TITLE
App has connected to desk but isn't communicating

### ISSUE THREAD

**Issue by codylg** [DWilliames/idasen-controller-mac#5]
Keen to get this app working as it looks great and I love that it can be controlled with scripts.

After connecting to my desk the app isn't able to read the current height of the desk and cannot move it up/down or to the predefined positions.

I have tried to reset my desk and have deleted the app, however I can't see where to wipe the app preferences so I can try to initialise the connection again. If I delete the app and download it again then it is already connected to the desk on open, but still cannot communicate.

<img width="347" alt="Screen Shot 2021-12-06 at 2 14 54 pm" src="https://user-images.githubusercontent.com/5643315/144786215-3eb9b8bb-4408-460b-a5d1-5c83cf39b7ac.png">

**Comment by yurazazik** [comment]
Hi Codylg, did u fix this problem?

**Comment by codylg** [comment]
@yurazazik I think this might have resolved itself? It has been connected and working fine. The issue possibly might have been that I had one or two other apps connected to the desk at the same time as I was testing a few out, but I'm not sure.
